### ISSUE TITLE
Evaluation runtime

### ISSUE THREAD

**Issue by bjoernpl** [daniel-furman/Polyglot-or-Not#12]
Thanks for the interesting work! 
Could you please provide some reference for how long these evaluations took to run? For example, how long does it take to run the monolingual evaluations on Llama 7b and 13b?

**Comment by daniel-furman** [comment]
Takes about 3 hours or so for the En-only subset with a llama 7b.

**Comment by bjoernpl** [comment]
Good to know, thanks :)
